/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Congruencias;
import GUI.*;
import controlador.*;
import lib.comun.LibComun;

/**
 *
 * @author netbeans
 */
public class Fundamental extends javax.swing.JFrame {
    Controlador c;
    javax.swing.JFrame ventanaAnterior;
    LibComun lc = new LibComun();
    /**
     * Creates new form MyS
     * @param c
     */
    public Fundamental(Controlador c, javax.swing.JFrame f) {
        initComponents();
        this.c = c;
        this.ventanaAnterior = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoRelacionFundamental = new javax.swing.JPanel();
        VariablesRelacionFundamental = new javax.swing.JPanel();
        k = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        aTxt = new javax.swing.JTextField();
        cTxt = new javax.swing.JTextField();
        kTxt = new javax.swing.JTextField();
        mTxt = new javax.swing.JTextField();
        v0Txt = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        nTxt = new javax.swing.JTextField();
        generar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        metodos = new javax.swing.JComboBox<>();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relacion Fundamental");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        GrupoRelacionFundamental.setBorder(javax.swing.BorderFactory.createTitledBorder("Relacion Fundamental"));

        VariablesRelacionFundamental.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables Relacion fundamental"));

        k.setText("k");

        m.setText("m");

        C.setText("c");

        a.setText("a");

        a1.setText("V0");

        javax.swing.GroupLayout VariablesRelacionFundamentalLayout = new javax.swing.GroupLayout(VariablesRelacionFundamental);
        VariablesRelacionFundamental.setLayout(VariablesRelacionFundamentalLayout);
        VariablesRelacionFundamentalLayout.setHorizontalGroup(
            VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                                        .addComponent(C)
                                        .addGap(26, 26, 26)
                                        .addComponent(cTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                                        .addComponent(k)
                                        .addGap(24, 24, 24)
                                        .addComponent(kTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                                .addComponent(m)
                                .addGap(24, 24, 24)
                                .addComponent(mTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(a)
                                .addGap(26, 26, 26)
                                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v0Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(VariablesRelacionFundamentalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(a1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        VariablesRelacionFundamentalLayout.setVerticalGroup(
            VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VariablesRelacionFundamentalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v0Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VariablesRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m))
                .addContainerGap())
        );

        N.setText("N");
        N.setToolTipText("Cantidad de numeros aleatorios a ser generados");

        javax.swing.GroupLayout GrupoRelacionFundamentalLayout = new javax.swing.GroupLayout(GrupoRelacionFundamental);
        GrupoRelacionFundamental.setLayout(GrupoRelacionFundamentalLayout);
        GrupoRelacionFundamentalLayout.setHorizontalGroup(
            GrupoRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VariablesRelacionFundamental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GrupoRelacionFundamentalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(N)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GrupoRelacionFundamentalLayout.setVerticalGroup(
            GrupoRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GrupoRelacionFundamentalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoRelacionFundamentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N)
                    .addComponent(nTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VariablesRelacionFundamental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        metodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fundamental", "Aditivo", "Multiplicativo", "Mixto" }));

        jMenu1.setText("Generacion de Numeros Aleatorios");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Metodo Congruencias");
        jMenu1.add(jMenuItem1);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GrupoRelacionFundamental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generar))
                    .addComponent(metodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(GrupoRelacionFundamental, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(generar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
        this.ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        MetodoCongruencias mc = this.c.getMc();
        String metodoAUtilizar = (String) this.metodos.getSelectedItem();
        int v0, a, c, k, m, n;
        
        /*
        * @TODO: Pasar la logica al controlador
        */
        
        /*
        * @TODO: dejar mas robusta esta parte, resistente a errores como 
        * casillas en blanco, letras/simbolos en vez de numeros.
        */
        
        /*
        * @TODO: programar logica para que se respeten los constraints de 
        * cada m'etodo indagar en las restricciones de cada uno de ellos
        */
        v0 = Integer.parseInt(this.v0Txt.getText());
        a = Integer.parseInt(this.aTxt.getText());
        c = Integer.parseInt(this.cTxt.getText());
        k = Integer.parseInt(this.kTxt.getText());
        m = Integer.parseInt(this.mTxt.getText());
        n = Integer.parseInt(this.nTxt.getText());
        
        /*
        * @TODO: Cambiar por archivo de configuracion mas flexible
        * @TODO: mostrar mensaje de donde se guarda el archivo generado
        * @TODO: 
        */
        if (metodoAUtilizar.toLowerCase().equals("fundamental")) {
            if (lc.escribirArchivo(mc.relacionFundamental(a, c, k, m, n))) {
                System.out.println("TODO BIEN.");
            } else {
                System.out.println("TODO MAL.");
            }
        } else if(metodoAUtilizar.toLowerCase().equals("aditivo")) {
            if (lc.escribirArchivo(mc.metodoAditivo(k, m, n))) {
                System.out.println("TODO BIEN.");
            } else {
                System.out.println("TODO MAL.");
            }
        } else if (metodoAUtilizar.toLowerCase().equals("multiplicativo")) {
            if (lc.escribirArchivo(mc.metodoMultiplicativo(v0, a, m, n))) {
                System.out.println("TODO BIEN.");
            } else {
                System.out.println("TODO MAL.");
            }   
        } else if (metodoAUtilizar.toLowerCase().equals("mixto")) {
            if (lc.escribirArchivo(mc.metodoMixto(v0, a, c, k, m, n))) {
                System.out.println("TODO BIEN.");
            } else {
                System.out.println("TODO MAL.");
            }
        }
        
        
    }//GEN-LAST:event_generarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C;
    private javax.swing.JPanel GrupoRelacionFundamental;
    private javax.swing.JLabel N;
    private javax.swing.JPanel VariablesRelacionFundamental;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JTextField aTxt;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JTextField cTxt;
    private javax.swing.JButton generar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel k;
    private javax.swing.JTextField kTxt;
    private javax.swing.JLabel m;
    private javax.swing.JTextField mTxt;
    private javax.swing.JComboBox<String> metodos;
    private javax.swing.JTextField nTxt;
    private javax.swing.JTextField v0Txt;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
