/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import transporte.Modelo;

/**
 *
 * @author urc
 */
public class TransporteGUI extends javax.swing.JFrame {
    // Objeto que se va a encargar de resolver el problema
    Modelo modelo;
    private int V0, V1, V2, a, c, k, m, n, cantMC;
    private String probabilidades;
    private int cantAsc = 1; // utilizado para la numeracion en el listado de probabilidades
    private double intervaloMIN, intervaloMAX;
    private String metodo;
    
    /*
        Variables del modelo de Transporte
    */
    private int TOTC;
    private double[] VECM, VECP, VECPAC;
    
    /**
     * Creates new form TransporteGUI
     */
    public TransporteGUI() {
        initComponents();
        this.configurar(this.cmbMetodos.getSelectedItem().toString());
        this.modelo = new Modelo(this.cmbMetodos.getSelectedItem().toString());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtV0 = new javax.swing.JTextField();
        txtV1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtV2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtK = new javax.swing.JTextField();
        txtM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbMetodos = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCantMC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIntMIN = new javax.swing.JTextField();
        txtIntMAX = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtProb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblProbAcumulada = new javax.swing.JLabel();
        addProbabilidad = new javax.swing.JButton();
        lblCantidadProbabilidadesPendiente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProbabilidades = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        simular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabel1.setText("N:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Semillas"));

        jLabel2.setText("V0:");

        jLabel3.setText("V1:");

        jLabel4.setText("V2:");

        jLabel5.setText("a:");

        jLabel6.setText("c:");

        jLabel7.setText("k:");

        jLabel8.setText("m:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtV0, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtV0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fundamental", "Aditivo", "Multiplicativo", "Mixto", "Fibonacci", "Java" }));
        cmbMetodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMetodosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMetodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cmbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Parametros Simulacion", jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion Marcas de Clase"));

        jLabel9.setText("Cantidad Marcas de clase:");
        jLabel9.setToolTipText("<html>\tSi la cantidad de probabilidades ingresada no es igual a la cantidad de marcas de clase <br>\n\tse rellenara a las marcas de clase superiores con probabilidad 0.<br><br>\n\tEJ: Si la cantidad de marcas de clase es de 4, y solo se ingresa un 20 como primer dato,<br>\n\tlas siguientes 3 marcas de clase se tomaran con probabilidad de 0%");

        txtCantMC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantMCFocusLost(evt);
            }
        });

        jLabel10.setText("Rango de Valores:");

        jLabel11.setText("a");
        jLabel11.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIntMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCantMC)
                    .addComponent(txtIntMAX, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIntMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIntMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel9.getAccessibleContext().setAccessibleDescription("");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Probabilidades"));

        jLabel12.setText("Probabilidad: ");

        txtProb.setToolTipText("");

        jLabel13.setText("%");

        jLabel14.setText("Probabilidad acumulada: ");

        lblProbAcumulada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProbAcumulada.setText("0");

        addProbabilidad.setText("+");
        addProbabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProbabilidadActionPerformed(evt);
            }
        });

        lblCantidadProbabilidadesPendiente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidadProbabilidadesPendiente.setText("cant");

        lstProbabilidades.setColumns(20);
        lstProbabilidades.setRows(5);
        jScrollPane2.setViewportView(lstProbabilidades);

        jLabel15.setText("%");

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtProb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProbAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadProbabilidadesPendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(limpiar)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtProb)
                        .addComponent(jLabel13))
                    .addComponent(addProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProbAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lblCantidadProbabilidadesPendiente)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Marcas de Clase y Probabilidades", jPanel4);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        simular.setText("Simular");
        simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simular)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(simular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMetodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMetodosItemStateChanged
        System.out.println("Elemento del Combo: "+ this.cmbMetodos.getSelectedItem().toString());
        this.configurar(this.cmbMetodos.getSelectedItem().toString());
        // Actualizamos el metodo que se usa para el modelo en el cambio del combo de metodos
        this.modelo = new Modelo(this.cmbMetodos.getSelectedItem().toString());
    }//GEN-LAST:event_cmbMetodosItemStateChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void addProbabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProbabilidadActionPerformed
        if ("".equals(this.txtCantMC.getText()) || this.txtCantMC.getText() == null ) {
            System.err.println("Se debe proporcionar las cantidad de marcas de clase a la cual\nsera mapeada cada probabilidad que se ingrese.");
        }
        if ("".equals(this.txtIntMAX.getText()) || this.txtIntMAX.getText() == null || "".equals(this.txtIntMIN.getText()) || this.txtIntMIN.getText() == null) {
            System.err.println("Se debe proporcionar un limite inferior y un limite superior\npara determinar el rango del intervalo.");
        }
        
        setConfigMC();
        int nuevaCant = Integer.parseInt(this.lblCantidadProbabilidadesPendiente.getText());
        if (!"0".equals(this.lblCantidadProbabilidadesPendiente.getText()) && Double.valueOf(this.lblProbAcumulada.getText())+Double.valueOf(this.txtProb.getText()) <= 100.0) {
            // Si es la primera vez no pone nada al inicio de la lista, esto evita que ponga un "\n" al principio
            if (String.valueOf(this.cantMC).equals(this.lblCantidadProbabilidadesPendiente.getText())) {
                this.lstProbabilidades.setText(String.valueOf(this.cantAsc)+" - "+this.txtProb.getText());
            } else {
                this.lstProbabilidades.setText(this.lstProbabilidades.getText()+"\n"+String.valueOf(this.cantAsc)+" - "+this.txtProb.getText());
            }
            // Actualiza la probabilidad acumulada 
            this.lblProbAcumulada.setText(String.valueOf(Double.valueOf(this.lblProbAcumulada.getText())+Double.valueOf(this.txtProb.getText())));
            // Disminuye la etiqueta que muestra la cantidad pendiente de probabilidades a ingresar
            nuevaCant = Integer.parseInt(this.lblCantidadProbabilidadesPendiente.getText()) - 1;
            this.cantAsc++;
        } else {
//            if (!"0".equals(this.lblCantidadProbabilidadesPendiente.getText())) {
//                int cantPendiente = Integer.parseInt(this.lblCantidadProbabilidadesPendiente.getText());
//                for (int i = 0; i < cantPendiente; i++) {
//                    System.out.println("cant pendiente:" + cantPendiente + ", i:"+i);
//                    String nTexto = this.txtProb.getText()+"\n0";
//                    this.lstProbabilidades.setText(nTexto);
//                }
//            }
        }
        
        
        this.lblCantidadProbabilidadesPendiente.setText(String.valueOf(nuevaCant));
        this.txtProb.setText("");
    }//GEN-LAST:event_addProbabilidadActionPerformed

    private void txtCantMCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantMCFocusLost
        this.lblCantidadProbabilidadesPendiente.setText(this.txtCantMC.getText());
    }//GEN-LAST:event_txtCantMCFocusLost

    private void simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularActionPerformed
        // Tomar todos los valores
        // Parametros Semilla
        this.V0 = !this.txtV0.getText().isEmpty() ? Integer.parseInt(this.txtV0.getText()) : 0;
        this.V1 = !this.txtV1.getText().isEmpty()? Integer.parseInt(this.txtV1.getText()) : 0;
        this.V2 = !this.txtV2.getText().isEmpty()? Integer.parseInt(this.txtV2.getText()) : 0;
        this.a = !this.txtA.getText().isEmpty()? Integer.parseInt(this.txtA.getText()) : 17;
        this.c = !this.txtC.getText().isEmpty()? Integer.parseInt(this.txtC.getText()) : 37;
        this.k = !this.txtK.getText().isEmpty()? Integer.parseInt(this.txtK.getText()) : 100;
        this.m = !this.txtM.getText().isEmpty()? Integer.parseInt(this.txtM.getText()) : 4000;
        this.n = !this.txtN.getText().isEmpty()? Integer.parseInt(this.txtN.getText()) : 25;

        
        // Parametros de Marcas de clase
        this.setConfigMC();
        // Parametro cadena de probabilidades
        this.probabilidades = this.lstProbabilidades.getText();
        // Hace que el objeto que va a resolver el problema conozca parametros necesarios para la resolucion del problema
        this.modelo.set_parametros(this.V0, this.V1, this.V2, this.a, this.c, this.k, this.m, this.n, this.probabilidades, this.cantMC, this.intervaloMAX, this.intervaloMIN);
        Resultados r = new Resultados(this, this.modelo);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simularActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        this.lstProbabilidades.setText("");
        this.lblCantidadProbabilidadesPendiente.setText(this.txtCantMC.getText()); 
        this.lblProbAcumulada.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void configurar(String metodo_seleccionado)
    {
        Parametro u = new Parametro();
        HashMap<String, Boolean> parametros = new HashMap<>();
        Iterator<Entry<String, Boolean>> it;
        switch(metodo_seleccionado.toLowerCase()){
            case "fundamental":
                parametros = u.getPARAMETROS_FUNDAMENTAL();
                break;
            case "aditivo":
                parametros = u.getPARAMETROS_ADITIVO();
                break;
            case "multiplicativo":
                parametros = u.getPARAMETROS_MULTIPLICATIVO();
                break;
            case "mixto":
                parametros = u.getPARAMETROS_MIXTO();
                break;
            case "fibonacci":
                parametros = u.getPARAMETROS_FIBONACCI();
                break;
            case "java":
                System.out.println("Estoy entrando donde debo");
                parametros = u.getPARAMETROS_JAVARANDOM();
                break;
        }
        it = parametros.entrySet().iterator();
        while (it.hasNext()) {
            Entry<String, Boolean> e = it.next();
            if (null != e.getKey().toLowerCase()) 
                switch (e.getKey().toLowerCase()) {
                case "v0":
                    if (e.getValue()) {this.txtV0.setText(""); this.txtV0.setEnabled(true);} else {this.txtV0.setText("0"); this.txtV0.setEnabled(false);}
                    break;
                case "v1":
                    if (e.getValue()) {this.txtV1.setText(""); this.txtV1.setEnabled(true);} else {this.txtV1.setText("0");this.txtV1.setEnabled(false);}
                    break;
                case "v2":
                    if (e.getValue()) {this.txtV2.setText(""); this.txtV2.setEnabled(true);} else {this.txtV2.setText("0");this.txtV2.setEnabled(false);}
                    break;
                case "a":
                    if (e.getValue()) {this.txtA.setText(""); this.txtA.setEnabled(true);} else {this.txtA.setText("0");this.txtA.setEnabled(false);}
                    break;
                case "c":
                    if (e.getValue()) {this.txtC.setText(""); this.txtC.setEnabled(true);} else {this.txtC.setText("0");this.txtC.setEnabled(false);}            
                    break;
                case "k":
                    if (e.getValue()) {this.txtK.setText(""); this.txtK.setEnabled(true);} else {this.txtK.setText("0");this.txtK.setEnabled(false);}
                    break;
                case "m":
                    if (e.getValue()) {this.txtM.setText(""); this.txtM.setEnabled(true);} else {this.txtM.setText("0");this.txtM.setEnabled(false);}
                    break;
                case "n":
                    if (e.getValue()) {this.txtN.setText(""); this.txtN.setEnabled(true);} else {this.txtN.setText("0");this.txtN.setEnabled(false);}
                    break;
                default:
                    break;
            }            
        }
        
        // Setea la lista de prob acumuladas en solo-lectura
        this.lstProbabilidades.setEditable(false);
    }

    private void setConfigMC()
    {
        this.cantMC = !this.txtCantMC.getText().isEmpty() ? Integer.parseInt(this.txtCantMC.getText()) : 6;
        this.intervaloMAX = !this.txtIntMAX.getText().isEmpty() ? Double.parseDouble(this.txtIntMIN.getText()) : 540.0;
        this.intervaloMIN = !this.txtIntMIN.getText().isEmpty() ? Double.parseDouble(this.txtIntMAX.getText()) : 860.0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProbabilidad;
    private javax.swing.JComboBox<String> cmbMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantidadProbabilidadesPendiente;
    private javax.swing.JLabel lblProbAcumulada;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea lstProbabilidades;
    private javax.swing.JButton salir;
    private javax.swing.JButton simular;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtCantMC;
    private javax.swing.JTextField txtIntMAX;
    private javax.swing.JTextField txtIntMIN;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtProb;
    private javax.swing.JTextField txtV0;
    private javax.swing.JTextField txtV1;
    private javax.swing.JTextField txtV2;
    // End of variables declaration//GEN-END:variables
}
